const data = {
  products: [
    {
      _id: "https://amzn.to/3tOlPol",
      name: "eye Lush1",
      category: "Shirts",
      image: "/images/eyelush.png",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "eye Lush2",
      category: "Shirts",
      image: "/images/eyelush.png",
      price: 120,
      countInStock: 20,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "eye Lush3",
      category: "Shirts",
      image: "/images/eyelush.png",
      price: 120,
      countInStock: 0,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "eye Lush4",
      category: "Shirts",
      image: "/images/eyelush.png",
      price: 120,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "eye Lush5",
      category: "Shirts",
      image: "/images/eyelush.png",
      price: 120,
      countInStock: 5,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "eye Lush6",
      category: "Shirts",
      image: "/images/eyelush.png",
      price: 120,
      countInStock: 12,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};

export default data;
